// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ContractInstanceId, ContractInstanceIdT } from '../common/contract-instance-id.js';


export class NotFound implements flatbuffers.IUnpackableObject<NotFoundT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NotFound {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNotFound(bb:flatbuffers.ByteBuffer, obj?:NotFound):NotFound {
  return (obj || new NotFound()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNotFound(bb:flatbuffers.ByteBuffer, obj?:NotFound):NotFound {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NotFound()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

instanceId(obj?:ContractInstanceId):ContractInstanceId|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ContractInstanceId()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startNotFound(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addInstanceId(builder:flatbuffers.Builder, instanceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, instanceIdOffset, 0);
}

static endNotFound(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // instance_id
  return offset;
}

static createNotFound(builder:flatbuffers.Builder, instanceIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  NotFound.startNotFound(builder);
  NotFound.addInstanceId(builder, instanceIdOffset);
  return NotFound.endNotFound(builder);
}

unpack(): NotFoundT {
  return new NotFoundT(
    (this.instanceId() !== null ? this.instanceId()!.unpack() : null)
  );
}


unpackTo(_o: NotFoundT): void {
  _o.instanceId = (this.instanceId() !== null ? this.instanceId()!.unpack() : null);
}
}

export class NotFoundT implements flatbuffers.IGeneratedObject {
constructor(
  public instanceId: ContractInstanceIdT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const instanceId = (this.instanceId !== null ? this.instanceId!.pack(builder) : 0);

  return NotFound.createNotFound(builder,
    instanceId
  );
}
}
