// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class StreamChunk implements flatbuffers.IUnpackableObject<StreamChunkT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StreamChunk {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStreamChunk(bb:flatbuffers.ByteBuffer, obj?:StreamChunk):StreamChunk {
  return (obj || new StreamChunk()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStreamChunk(bb:flatbuffers.ByteBuffer, obj?:StreamChunk):StreamChunk {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StreamChunk()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

streamId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

index():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

total():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

data(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

dataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dataArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startStreamChunk(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addStreamId(builder:flatbuffers.Builder, streamId:number) {
  builder.addFieldInt32(0, streamId, 0);
}

static addIndex(builder:flatbuffers.Builder, index:number) {
  builder.addFieldInt32(1, index, 0);
}

static addTotal(builder:flatbuffers.Builder, total:number) {
  builder.addFieldInt32(2, total, 0);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, dataOffset, 0);
}

static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endStreamChunk(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 10) // data
  return offset;
}

static createStreamChunk(builder:flatbuffers.Builder, streamId:number, index:number, total:number, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  StreamChunk.startStreamChunk(builder);
  StreamChunk.addStreamId(builder, streamId);
  StreamChunk.addIndex(builder, index);
  StreamChunk.addTotal(builder, total);
  StreamChunk.addData(builder, dataOffset);
  return StreamChunk.endStreamChunk(builder);
}

unpack(): StreamChunkT {
  return new StreamChunkT(
    this.streamId(),
    this.index(),
    this.total(),
    this.bb!.createScalarList<number>(this.data.bind(this), this.dataLength())
  );
}


unpackTo(_o: StreamChunkT): void {
  _o.streamId = this.streamId();
  _o.index = this.index();
  _o.total = this.total();
  _o.data = this.bb!.createScalarList<number>(this.data.bind(this), this.dataLength());
}
}

export class StreamChunkT implements flatbuffers.IGeneratedObject {
constructor(
  public streamId: number = 0,
  public index: number = 0,
  public total: number = 0,
  public data: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const data = StreamChunk.createDataVector(builder, this.data);

  return StreamChunk.createStreamChunk(builder,
    this.streamId,
    this.index,
    this.total,
    data
  );
}
}
