// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { UserInputResponse, UserInputResponseT } from '../client-request/user-input-response.js';
import { ApplicationMessage, ApplicationMessageT } from '../common/application-message.js';


export enum InboundDelegateMsgType {
  NONE = 0,
  common_ApplicationMessage = 1,
  UserInputResponse = 2
}

export function unionToInboundDelegateMsgType(
  type: InboundDelegateMsgType,
  accessor: (obj:ApplicationMessage|UserInputResponse) => ApplicationMessage|UserInputResponse|null
): ApplicationMessage|UserInputResponse|null {
  switch(InboundDelegateMsgType[type]) {
    case 'NONE': return null; 
    case 'common_ApplicationMessage': return accessor(new ApplicationMessage())! as ApplicationMessage;
    case 'UserInputResponse': return accessor(new UserInputResponse())! as UserInputResponse;
    default: return null;
  }
}

export function unionListToInboundDelegateMsgType(
  type: InboundDelegateMsgType, 
  accessor: (index: number, obj:ApplicationMessage|UserInputResponse) => ApplicationMessage|UserInputResponse|null, 
  index: number
): ApplicationMessage|UserInputResponse|null {
  switch(InboundDelegateMsgType[type]) {
    case 'NONE': return null; 
    case 'common_ApplicationMessage': return accessor(index, new ApplicationMessage())! as ApplicationMessage;
    case 'UserInputResponse': return accessor(index, new UserInputResponse())! as UserInputResponse;
    default: return null;
  }
}
